/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.museautomation.runnner.server;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PingTest
    {
    @Test void testSomeLibraryMethod() {
        assertTrue(false, "not net implemented any tests");
    }
}
